version: '3'
services:
  app:
    build:
      context: ./php
    volumes:
      - './../:/var/www/html'
      - './php/sites:/etc/apache2/sites-available'
      - './data/dev:/home/dev'
    links:
      - db
    depends_on:
      - db
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    networks:
      app_net:
        ipv4_address: 172.16.1.94
  db:
    image: 'mysql:5.7'
    volumes:
      - './base:/var/lib/mysql'
      - './sql:/home/sql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      app_net:
        ipv4_address: 172.16.1.93
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.88/29
